spring:
  config:
    import: "optional:classpath:application-secrets.yaml"
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  devtools:
    restart:
      enabled: false